CREATE TABLE folders(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);

-- insert some test data
-- Using a multi-row insert statement here
insert into folders
    (name)
values
    ('Monday Folder'),
    ('Tuesday Folder'),
    ('Wednesday Folder'),
    ('Thursday Folder'),
    ('Friday Folder'),
    ('Saturday Folder'),
    ('Sunday Folder');